### ISSUE TITLE
broken links in README.new_fusepy_api

### ISSUE THREAD

**Issue by ensonic** [libfuse/python-fuse#2]
this link does not work.
http://fuse.sourceforge.net/wiki/index.php/FusePython

It would really be awesome to have some docs online (e.g. on https://readthedocs.org/)

**Comment by Nikratio** [comment]
Thanks for the report. But please note that this project is currently orphaned. If you're interested in taking over maintenance, please file an issue. Ideally, this would include some reasons why you're qualified and some pull requests as additional evidence (so we know the project will be in good hands).

**Comment by ensonic** [comment]
:/ I don't have the capacity to take over another project. If the docs are hosted somewhere (and you tell me where) I'll send PRs to fix links.

Consider a banner to tell that you look for a maintainer.

**Comment by Celelibi** [comment]
There the same broken link in the FAQ file.
Just saying that here so if someone fix it he could fix both at once.
