### ISSUE TITLE
hello.py returns -22 on read

### ISSUE THREAD

**Issue by sundhaug92** [libfuse/python-fuse#23]

**Comment by sundhaug92** [comment]
Seems to be because `bytes` is being returned rather than `str`, so relates to py3 compat

**Comment by sdelafond** [comment]
I'm swamped right now but I'll gladly accept a PR fixing that.

**Comment by sdelafond** [comment]
Could you provide context and minimal reproduction steps for this error?

**Comment by sundhaug92** [comment]
I'm sorry, it's been almost 4 years. I was probably running Ubuntu and using python 3.x, but I don't remember a lot

**Comment by glensc** [comment]
works with python 3.11

```
$ python example/hello.py tmp 

$ ls -lla tmp 
total 4
drwxr-xr-x  2 root wheel   0 Jan  1  1970 ./
drwxr-xr-x 30 glen staff 960 Jan 15 03:44 ../
-r--r--r--  1 root wheel  13 Jan  1  1970 hello

$ cat tmp/hello
Hello World!
```
