### ISSUE TITLE
how to exit fuse process

### ISSUE THREAD

**Issue by Aknifejackzhmolong** [libfuse/python-fuse#26]
`Ctrl+C` can't stop it

**Comment by Rprabudeva** [comment]
the extra clarification in the comment of fuse_exit() would
be helpful

**Comment by Aknifejackzhmolong** [comment]
I found I can use a "unmount" command to stop it

**Comment by cmcqueen** [comment]
I still would like to be able to cleanly end a python-fuse program using Ctrl-C (SIGTERM or SIGINT). See also issue #45.
