### ISSUE TITLE
inconsistent fuse write chunk size for different versions of windows

### ISSUE THREAD

**Issue by rahulrane50** [libfuse/python-fuse#4]
I am using python fuse to intercept my application writes. My application is writing in 4K chunks on file present at fuse mount point and for windows 2008 and 2012 server edition fuse write is comming in 4K chunks but for windows 2003 fuse is receiving 512 and 3546 fuse write requests for each of 4K application write. Why the fuse is behaving differently for windows 2k3? 
win2k3 drive details : 
bytes per sector : 512 
bytes per cluster : 4096 
sectors per cluster : 8 
bytes per volume : 32201936896 
sectors per volume : 7861801 
clusters per volume : 982725 
initialized mft records : 19504 
mft records in use : 19469 
mft records percentage : 99 
bytes of free space : 27737296896 
sectors of free space : 54174408 
clusters of free space : 6771801 
percentage free space : 86 
bytes of user data : 4340850688 
sectors of user data : 8478224 
clusters of user data : 1059778 
percentage user data : 13 
bytes of metadata : 123789312 
sectors of metadata : 241776 
clusters of metadata : 30222 
percentage metadata : 0

Please help me in understanding this behavior.

**Comment by Nikratio** [comment]
There is no FUSE for Windows. Thus I presume you are running FUSE on Linux, and accessing the mountpoint via Samba. In this case the application that generates the write requests is samba, not your application. This is what causes the different chunk size.

**Comment by glensc** [comment]
there is some fuse on windows
- https://github.com/billziss-gh/winfuse
