### ISSUE TITLE
where to and how to specify big_writes option inside python file?

### ISSUE THREAD

**Issue by Gorparth** [libfuse/python-fuse#40]
I've implemented GDriveFS and OnedriveFS, I've inherited fuse.Fuse in my defined class, and instance is created like this 
if __name__ == '__main__':
    authed_usr = GDrive()
    gdrivefs = GoogleDriveFS(version = '%prog ' + '0.0.1',
               usage = 'GoogleDrive Filesystem ' + fuse.Fuse.fusage,
               dash_s_do = 'setsingle')
    gdrivefs.parse(errex = 1)
    gdrivefs.flags = 0
    gdrivefs.main()

In this what should I add to make read/write speed faster, (big_writes,max_readahed,max_write,etc),
or 
how to add these parameters with exact syntax?

**Comment by MyForest** [comment]
I did it like [this](https://github.com/MyForest/SolidFS/blob/0856b58796ba7f43e1e6c1773e547c81d7badf51/src/solidfs.py#L546):

```python
    server.fuse_args.optdict["max_write"] = 131072
    server.fuse_args.optdict["max_read"] = 131072
    server.fuse_args.optdict["max_background"] = 16
```

before I even added any options.

Notably this allows the user to specify different values to override my values.
