### ISSUE TITLE
PY_SSIZE_T_CLEAN should be defined before importing Python.h as of 3.10

### ISSUE THREAD

**Issue by antevens** [libfuse/python-fuse#41]
I think this is a pretty simple issue, was debugging python-fuse on 3.10 and found this in my log:

```
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
   unique: 84, error: -22 (Invalid argument), outsize: 16
```

https://docs.python.org/3/c-api/intro.html

Let me know if you want a merge/pull request.

**Comment by sdelafond** [comment]
Yes if you can do that it'd be great.
