### ISSUE TITLE
wrong library installed - x86_64 instead of arm64

### ISSUE THREAD

**Issue by hananbeer** [libfuse/python-fuse#48]
I have mac m1 arm64.

whenever I do pip install fuse-python (which is btw reversed from this repo name) it installs the library under:
`~/opt/miniconda3/lib/python3.9/site-packages/fuseparts/_fuse.cpython-39-darwin.so`

however it is the wrong architecture:
```
file ~/opt/miniconda3/lib/python3.9/site-packages/fuseparts/_fuse.cpython-39-darwin.so
~/opt/miniconda3/lib/python3.9/site-packages/fuseparts/_fuse.cpython-39-darwin.so: Mach-O 64-bit bundle x86_64
```

I have confirmed other libs are installed properly so it seems isolated to fuse-python.

**Comment by glensc** [comment]
no version info in bug report. looks fine with fuse-python 1.0.6

```
$ pip list | grep fuse
fuse-python 1.0.6

$ file .direnv/python-3.11/lib/python3.11/site-packages/fuseparts/_fuse.cpython-311-darwin.so
.direnv/python-3.11/lib/python3.11/site-packages/fuseparts/_fuse.cpython-311-darwin.so: Mach-O 64-bit bundle arm64
```

**Comment by sdelafond** [comment]
@hananbeer can you confirm `1.0.6` works for you?

**Comment by hananbeer** [comment]
this was a year ago. I don't even remember what I was trying to do 😅

anyhow I upgraded from 1.0.5 to 1.0.7 and it installs the correct lib now.
come to think about it, it may be related to `arch` command. I'm not sure.

thanks.
