### ISSUE TITLE
Ubuntu 16.04 pkg-config no longer has option --usage so install fails?

### ISSUE THREAD

**Issue by ekristen** [libfuse/python-fuse#5]
Anyone else seen that pkg-config seems to no longer support --usage as a CLI option and causes python-fuse to fail to install from pip?

**Comment by sdelafond** [comment]
This would not cause the install to fail: --usage is only used if pkg-config was not able to find libfuse on your system.
I'll submit a PR anyway, so the error message returned in this case is more helpful.
