### ISSUE TITLE
Wiki python 3 version

### ISSUE THREAD

**Issue by glensc** [libfuse/python-fuse#54]
https://github.com/libfuse/python-fuse/wiki example listing at bottom of the wiki page does not run on python 3.

Also, should it be moved to the project itself? it's just 1 commit there (`https://github.com/libfuse/python-fuse.wiki.git`) could just cherry-pick and apply the fix from below.

Attached fixed version:
- [CupsFS.py.txt](https://github.com/libfuse/python-fuse/files/13540746/CupsFS.py.txt) 3.8K

**Comment by glensc** [comment]
Actually, I only syntax fixed it, things like these need 2to3 as well: `self.printers.has_key`

**Comment by sdelafond** [comment]
The main value of `CupFS.py` is in the design and development process described in the rest of the wiki page. I agree the code itself should be updated for python3, but then the rest of that wiki page should also reflect the changes. Would you be willing to do that?

**Comment by glensc** [comment]
so, you have no opinion on putting the source to this project repo?

I would see this like:
1. the cupsfs.py is put to this repo (I can create pr with importing history)
2. the snippets in wiki is updated and full source listing is linked to this repo (I can provide commits to pull)

this way the cupsfs is hopefully updated with rest of the source code.

maybe the whole wiki content should be put as README.cupsfs as there's README.new_fusepy_api

**Comment by sdelafond** [comment]
>     1. the cupsfs.py is put to this repo (I can create pr with importing history)
> 
>     2. the snippets in wiki is updated and full source listing is linked to this repo (I can provide commits to pull)

I'll accept both those changes together.

> maybe the whole wiki content should be put as README.cupsfs as there's README.new_fusepy_api

We can see about that later on.

**Comment by glensc** [comment]
> I'll accept both those changes together.

please elaborate what you mean. wiki is in different git repo, how to provide them together?

**Comment by sdelafond** [comment]
I understand this won't be a single targetting one repo; I mean we want to do both changes, not just either one, and roughly at the same time. Is this clearer?

**Comment by sdelafond** [comment]
Sure, we can go that route too.
