### ISSUE TITLE
How to prevent overlapping calls to read?

### ISSUE THREAD

**Issue by moefear85** [libfuse/python-fuse#57]
Hi,

I'm a noob in both fuse and python-fuse. I've implemented the read(...) callback, but when I access a file from the outside, the read callback gets executed concurrently more than once, and even though I'm trying to access the data in order, the size and offset arguments passed to read seem to indicate it is getting called out of order (non-sequentially).

How do I prevent this? I don't want another call to read() to be triggered before the first one has fully completed.

Also, the mount options are a bit confusing. How do I pass command line arguments when I'm not creating the Fuse object from the command line? I'd like to let any user, specifically root, be able to access the fuse filesystem even when it's running as a normal user process.

**Comment by glensc** [comment]
without knowing the internals of fuse or this library, you can prevent concurrent access with lock:
- https://superfastpython.com/lock-vs-semaphore-in-python/

**Comment by moefear85** [comment]
thx im using them. i also discovered the -s option.
