### ISSUE TITLE
Is this repository still being maintained or should we be using fusepy?

### ISSUE THREAD

**Issue by kunallillaney** [libfuse/python-fuse#6]
@sectorsize512

**Comment by Nikratio** [comment]
Check out the "maintainer wanted" section right on the project page: https://github.com/libfuse/python-fuse

**Comment by sectorsize512** [comment]
@Nikratio,

Let me try to detail a bit more on @kunallillaney's question. We are thinking to use FUSE python binding for a prototype of a new file system. There are two bindings implementations available:

1) python-fuse (https://github.com/libfuse/python-fuse)

This is this project. It is in the official libfuse organization but is not maintained.

2) fusepy (https://github.com/terencehonles/fusepy)

This project is outside of "official" libfuse organization but has a maintainer and seems to have an active community.

So, as a chief of of the whole libfuse organization, @Nikratio, what are your vision on the fate of those two projects? E.g., is it possible that fusepy will replace python-fuse completely? Or there some benefits of python-fuse that justify the existance of two project? Your thoughts and advise are highly appreciated!

Thanks,
Vasily

**Comment by Nikratio** [comment]
Unless someone steps about to maintain python-fuse, I don't think this project has any future. About fusepy I know very little, so I can't comment. I would recommend to use python-llfuse if you can (https://bitbucket.org/nikratio/python-llfuse/). This is not part of libfuse, but maintained by me as well.

**Comment by sectorsize512** [comment]
Thank you for clarification, @Nikratio, this helps a lot. In fact, we would **prefer** to use low-level FUSE API, so we will give a try to https://bitbucket.org/nikratio/python-llfuse/

Do you think it can become part of libfuse organization some time in the future? That wpuld make it more "official", visible, and attract users :)

Vasily

**Comment by Nikratio** [comment]
I have thought about that, but then thought it odd to elevate the Python bindings this way - after all, there are a number of Python bindings for other languages out there that aren't included in libfuse either.
