### ISSUE TITLE
Add more wheels to pypi

### ISSUE THREAD

**Issue by glensc** [libfuse/python-fuse#63]
Seems this added some wheel:
- https://github.com/libfuse/python-fuse/commit/6f0921aa0a8248d34b0573a98b2c9327be52b78a

where is that executed? could not find github actions workflow, so on developer machine manually?
are you interested of automating this on git tag push instead?

 
anyway, currently is uploaded:

```
fuse_python-1.0.7-cp312-cp312-manylinux_2_28_x86_64.whl (186.5 kB view hashes)
```

yet I'm interested in `fuse_python-1.0.7-cp311-cp311-linux_aarch64.whl`.

also: can just `aarch64` wheel be added regardless of python version?

**Comment by sdelafond** [comment]
Sure, we can automate the creation of various wheels in a GH worflow. Please put as little logic as possible in there, and instead add the required variables/target to the existing Makefile.

**Comment by glensc** [comment]
It first means setting up publishing via GHA, as currently, I think you publish to pypi manually?

**Comment by sdelafond** [comment]
Nah, sorry, I don't want to publish through GHA. Creating the artifacts themselves upon tag push is fine though.

**Comment by glensc** [comment]
to be clear, there are no artifacts published right now with CI job on tags, and it must be added first?

**Comment by glensc** [comment]
and upload artifacts to github release? or leave in artifact storage?

**Comment by glensc** [comment]
can you make release meanwhile? 

i'll be able to validate if those wheels are suitable for my system with installation with pipx, as noted in issue body, in need cp311-linux_aarch64.

or what do you mean? you'll publish wheels for previous releases (as well)?

**Comment by glensc** [comment]
the idea of publishing wheels to github release was that you can download them and upload to pypi. they are added to each release action too, just thought finding from github release is easier to find them.

**Comment by sdelafond** [comment]
For validating the wheels, you don't need a release right now: the whole point of putting all the logic in the Makefile was so you could build and test them locally.

For the next release, I can upload to pypi the wheels built by GitHub, but only once the `sdist` is also created from GitHub actions: I don't want to mix locally-generated artifacts with GitHub-generated ones.

I'll look into adding that `sdist` creation soon, unless you beat me to it of course.

**Comment by glensc** [comment]
I wanted wheels for the specified platform, so I could install my program with pipx without installing the development toolchain. can you add wheels for cp311-cp311-linux_aarch64 to last release or make new release?

**Comment by sdelafond** [comment]
As I said in my previous comment a new release will only happen after I add `sdist` support to GH artifacts. I just added the wheel you need in pypi:

https://pypi.org/project/fuse-python/#files
https://files.pythonhosted.org/packages/be/9c/3b6597e4a140ddb97781c762695aae5954a3a8ecf5a20977e995cc01fd4f/fuse_python-1.0.7-cp311-cp311-manylinux_2_28_aarch64.whl

**Comment by glensc** [comment]
thanks. works as expected!

```
$ pipx install plex-fuse
  installed package plex-fuse 0.3.3, installed using Python 3.11.2
  These apps are now globally available
    - plex-fuse
done!  🌟 
```

**Comment by sdelafond** [comment]
We can probably close this ticket, then. I'll track `sdist` support in another one.
