### ISSUE TITLE
Support for being installed in dependabot

### ISSUE THREAD

**Issue by glensc** [libfuse/python-fuse#71]
I reported this issue:
- https://github.com/dependabot/dependabot-core/issues/9515

there's probably something that can be done this project side, my first guess is that wheel is needed for their platform.

the idea of not requiring setup.py to have  build deps installed was already thrown out:
- https://github.com/libfuse/python-fuse/issues/67#issuecomment-1991687243

**Comment by sdelafond** [comment]
1.0.8 should fix that.

**Comment by glensc** [comment]
Confirmed now:
- https://github.com/glensc/plex-fuse/pull/113
